"""
Pydantic Models for the Phishing Detection XAI API.
Defines request/response schemas for the FastAPI endpoints.
"""

from pydantic import BaseModel, Field
from typing import List, Optional


class EmailRequest(BaseModel):
    """Request model for email analysis."""
    email_text: str = Field(
        ...,
        min_length=10,
        max_length=50000,
        description="The full text content of the email to analyze",
        examples=["Dear user, your account has been compromised. Click here to verify your identity immediately."]
    )


class SHAPFeature(BaseModel):
    """A single SHAP feature with its importance value."""
    feature: str = Field(..., description="Name of the feature")
    importance: float = Field(..., description="SHAP importance value (absolute)")
    direction: str = Field(..., description="'phishing' or 'legitimate' — which class this feature pushes toward")


class LIMEHighlight(BaseModel):
    """A single LIME token highlight."""
    token: str = Field(..., description="The highlighted token/word")
    weight: float = Field(..., description="LIME weight — positive means phishing, negative means legitimate")


class AnalysisResponse(BaseModel):
    """Full analysis response with classification, confidence, and explanations."""
    classification: str = Field(..., description="'phishing' or 'legitimate'")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Model confidence (0.0 to 1.0)")
    shap_features: List[SHAPFeature] = Field(
        ...,
        min_length=1,
        max_length=10,
        description="Top 10 SHAP features driving the prediction"
    )
    lime_highlights: List[LIMEHighlight] = Field(
        ...,
        description="LIME token highlights showing word-level contributions"
    )
    llm_explanation: str = Field(
        ...,
        description="Natural language explanation generated by an LLM"
    )
    model_used: str = Field(
        default="ensemble",
        description="Which model produced the classification"
    )


class HealthResponse(BaseModel):
    """Health check response."""
    status: str = Field(default="healthy")
    model_loaded: bool = Field(default=False)
    version: str = Field(default="1.0.0")


class BatchEmailRequest(BaseModel):
    """Request model for batch email analysis (used in adversarial testing)."""
    emails: List[str] = Field(..., description="List of email texts to analyze")


class BatchAnalysisResponse(BaseModel):
    """Batch analysis response."""
    results: List[AnalysisResponse]
    total: int
    phishing_count: int
    legitimate_count: int
    evasion_rate: Optional[float] = Field(
        None, description="Evasion rate if all inputs are known phishing"
    )
